# Generated by Django 3.0.6 on 2020-08-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200729_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ocupation',
            field=models.TextField(blank=True),
        ),
    ]
