# Generated by Django 2.0.2 on 2020-08-11 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200807_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='category_id',
        ),
    ]
