# Generated by Django 3.0.6 on 2020-08-11 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_remove_profile_category_id'),
        ('registration', '0004_remove_profile_ocupation'),
    ]

    operations = [
    ]
